## Using PyTorch Tensors 

A PyTorch Tensor is basically the same as a numpy multidimensional array: it does not know
anything about deep learning or computational graphs or gradients, and is just
a generic n-dimensional array to be used for arbitrary numeric computation.

The biggest difference between a numpy array and a PyTorch Tensor is that
a PyTorch Tensor can run on either CPU or GPU. To run operations on the GPU,
just cast the Tensor to a cuda datatype.

(This example is adapted from: https://pytorch.org/tutorials/beginner/pytorch_with_examples.html )

### Basic tensor matrix operations

In [1]:
import torch

# Simple matrix
m1 = torch.ones(3, 4)
print('Matrix m1: \n', m1)
print(m1.shape,"\n")

# Another (random) matrix
m2 = torch.rand(3, 4) # fill 3x4 matrix with uniform random numbers in [0,1] interval
print('Matrix m2: \n', m2)
print(m2.shape,"\n")

# Transpose of a matrix
print('Matrix m2^T: \n', m2.t())
print(m2.t().shape,"\n")

# Matrix operations
m3 = m1*m2      # Not a matrix multiplication ! Here each value in matrix m1 are multiplied by value m2
print('Matrix m3: \n', m3)
print(m3.shape,"\n")

# Matrix multiplication using torch.mm
m4 = m1.mm(m2.t())
print('Matrix m4: \n', m4)
print(m4.shape,"\n")

# Matrix multiplication using torch.matmul
m5 = m1.matmul(m2.t())
print('Matrix m5: \n', m5)
print(m5.shape,"\n")

# For matrix-vector multiplication there is also the possibility to use torch.mv
vec = torch.tensor([1.0,2.0,3.0])
print(torch.matmul(m5, vec))

Matrix m1: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([3, 4]) 

Matrix m2: 
 tensor([[0.1157, 0.4705, 0.1604, 0.6519],
        [0.5901, 0.3330, 0.9829, 0.5998],
        [0.5548, 0.0507, 0.7762, 0.8113]])
torch.Size([3, 4]) 

Matrix m2^T: 
 tensor([[0.1157, 0.5901, 0.5548],
        [0.4705, 0.3330, 0.0507],
        [0.1604, 0.9829, 0.7762],
        [0.6519, 0.5998, 0.8113]])
torch.Size([4, 3]) 

Matrix m3: 
 tensor([[0.1157, 0.4705, 0.1604, 0.6519],
        [0.5901, 0.3330, 0.9829, 0.5998],
        [0.5548, 0.0507, 0.7762, 0.8113]])
torch.Size([3, 4]) 

Matrix m4: 
 tensor([[1.3984, 2.5058, 2.1929],
        [1.3984, 2.5058, 2.1929],
        [1.3984, 2.5058, 2.1929]])
torch.Size([3, 3]) 

Matrix m5: 
 tensor([[1.3984, 2.5058, 2.1929],
        [1.3984, 2.5058, 2.1929],
        [1.3984, 2.5058, 2.1929]])
torch.Size([3, 3]) 

tensor([12.9888, 12.9888, 12.9888])


### More operations (power, sum, clamp, ...)

(See even more basic operations here: https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/)

In [2]:
mat = torch.rand(3, 4)
print(mat)

# Takes the power of each element in input
print(mat.pow(3))

# Returns the sum of all elements in the input tensor
print(mat.sum())

# Clamp all elements in input into the range [ min, max ] and return a resulting tensor
print(mat.clamp(0.3,0.7))

tensor([[0.3053, 0.3329, 0.1608, 0.3585],
        [0.2057, 0.0540, 0.3088, 0.3913],
        [0.1058, 0.3738, 0.0864, 0.2156]])
tensor([[0.0285, 0.0369, 0.0042, 0.0461],
        [0.0087, 0.0002, 0.0294, 0.0599],
        [0.0012, 0.0522, 0.0006, 0.0100]])
tensor(2.8989)
tensor([[0.3053, 0.3329, 0.3000, 0.3585],
        [0.3000, 0.3000, 0.3088, 0.3913],
        [0.3000, 0.3738, 0.3000, 0.3000]])


### Convertion to numpy array

In [3]:
import numpy as np

# convertion PyTorch -> numpy
a = torch.randn(5)
b = a.numpy()

# convertion numpy -> PyTorch
c = torch.from_numpy(b)

print(a)
print(b)
print(c)

tensor([-1.7202,  0.8410, -0.3200,  1.4264,  1.1526])
[-1.7201914   0.8410047  -0.32003662  1.42642     1.1526212 ]
tensor([-1.7202,  0.8410, -0.3200,  1.4264,  1.1526])


### Autograd

A PyTorch Tensor represents a node in a computational graph. If ``x`` is a
Tensor that has ``x.requires_grad=True`` then ``x.grad`` is another Tensor
holding the gradient of ``x`` with respect to some scalar value.

Example for simple regression (adapted from S. Sviridov lecture):

In [4]:
# Simple regression example
x = [1., 2., 3., 4., 5.]           # data
y = [10., 20., 30., 40., 50.]      # target values

# Gradients will be calculated w.r.t this tensors (has "requires_grad=True")
w = torch.tensor([1.],requires_grad=True)

# Number of loops on all sample
for epoch in range(5):
    
    # Loop on data events and target values
    for x_i, y_i in zip(x, y):
        
        # compute predicted target variable
        y_pred = x_i * w
                
        # compute Mean Squared Error (MSE)
        loss = (y_pred - y_i) ** 2
        
        # With PyTorch we can automatically compute the derivative of the loss 
        # w.r.t. the tensors that have requires_grad set to True (i.e. w and b).
        # compute gradients
        loss.backward()
                        
        print('\t x=%.1f y=%.1f, w=%.2f, dloss/dw=%.1f' % (x_i, y_i, w.data, w.grad.data))
                
        # make one step towards the local minima, with learning rate 0.01
        w.data -= 0.01 * w.grad.data
        
        # clear gradients after updating weights
        w.grad.data.zero_()
        
    print('Loss at epoch #%d: %.6f \n' % (epoch+1, loss.data[0]))

print('Final: w = %.4f' % (w.data))


	 x=1.0 y=10.0, w=1.00, dloss/dw=-18.0
	 x=2.0 y=20.0, w=1.18, dloss/dw=-70.6
	 x=3.0 y=30.0, w=1.89, dloss/dw=-146.1
	 x=4.0 y=40.0, w=3.35, dloss/dw=-212.9
	 x=5.0 y=50.0, w=5.48, dloss/dw=-226.2
Loss at epoch #1: 511.797760 

	 x=1.0 y=10.0, w=7.74, dloss/dw=-4.5
	 x=2.0 y=20.0, w=7.78, dloss/dw=-17.7
	 x=3.0 y=30.0, w=7.96, dloss/dw=-36.7
	 x=4.0 y=40.0, w=8.33, dloss/dw=-53.5
	 x=5.0 y=50.0, w=8.86, dloss/dw=-56.9
Loss at epoch #2: 32.337894 

	 x=1.0 y=10.0, w=9.43, dloss/dw=-1.1
	 x=2.0 y=20.0, w=9.44, dloss/dw=-4.5
	 x=3.0 y=30.0, w=9.49, dloss/dw=-9.2
	 x=4.0 y=40.0, w=9.58, dloss/dw=-13.5
	 x=5.0 y=50.0, w=9.71, dloss/dw=-14.3
Loss at epoch #3: 2.043265 

	 x=1.0 y=10.0, w=9.86, dloss/dw=-0.3
	 x=2.0 y=20.0, w=9.86, dloss/dw=-1.1
	 x=3.0 y=30.0, w=9.87, dloss/dw=-2.3
	 x=4.0 y=40.0, w=9.89, dloss/dw=-3.4
	 x=5.0 y=50.0, w=9.93, dloss/dw=-3.6
Loss at epoch #4: 0.129104 

	 x=1.0 y=10.0, w=9.96, dloss/dw=-0.1
	 x=2.0 y=20.0, w=9.96, dloss/dw=-0.3
	 x=3.0 y=30.0, w=9.97, dloss/d

### Exercice
Now we have the following data. How should be modified the above code ? How many epochs are needed for convergence ?


In [6]:
# Now we have the following data. How should be modified the above code 
x = [1., 2., 3., 4., 5., 6., 7., 8., 9., 10.]           # data
y = [15., 25., 35., 45., 55., 65., 75., 85., 95., 105.] # target values

# Gradients will be calculated w.r.t these two tensors (have "requires_grad=True")
w = torch.tensor([1.],requires_grad=True)
b = torch.tensor([0.],requires_grad=True)

for epoch in range(100):
    
    for x_i, y_i in zip(x, y):
        
        # compute predicted target variable
        y_pred = x_i * w + b
                
        # compute Mean Squared Error (MSE)
        loss = (y_pred - y_i) ** 2
        
        # With PyTorch we can automatically compute the derivative of the loss 
        # w.r.t. the tensors that have requires_grad set to True (i.e. w and b).
        # compute gradients
        loss.backward()
                        
        print('\t x=%.1f y=%.1f, w=%.2f, b=%.2f, dloss/dw=%.1f, dloss/db=%.1f' % (x_i, y_i, w.data, b.data, w.grad.data, b.grad.data))
                
        # make one step towards the local minima, with learning rate 0.01
        w.data -= 0.01 * w.grad.data
        b.data -= 0.01 * b.grad.data
        
        # clear gradients after updating weights
        w.grad.data.zero_()
        b.grad.data.zero_()
        
    print('Loss at epoch #%d: %.6f \n' % (epoch+1, loss.data[0]))

print('Final: w = %.4f, b = %4f' % (w.data, b.data))


	 x=1.0 y=15.0, w=1.00, b=0.00, dloss/dw=-28.0, dloss/db=-28.0
	 x=2.0 y=25.0, w=1.28, b=0.28, dloss/dw=-88.6, dloss/db=-44.3
	 x=3.0 y=35.0, w=2.17, b=0.72, dloss/dw=-166.7, dloss/db=-55.6
	 x=4.0 y=45.0, w=3.83, b=1.28, dloss/dw=-227.1, dloss/db=-56.8
	 x=5.0 y=55.0, w=6.10, b=1.85, dloss/dw=-226.3, dloss/db=-45.3
	 x=6.0 y=65.0, w=8.37, b=2.30, dloss/dw=-150.0, dloss/db=-25.0
	 x=7.0 y=75.0, w=9.87, b=2.55, dloss/dw=-47.3, dloss/db=-6.8
	 x=8.0 y=85.0, w=10.34, b=2.62, dloss/dw=5.4, dloss/db=0.7
	 x=9.0 y=95.0, w=10.29, b=2.61, dloss/dw=3.3, dloss/db=0.4
	 x=10.0 y=105.0, w=10.25, b=2.61, dloss/dw=2.7, dloss/db=0.3
Loss at epoch #1: 0.018289 

	 x=1.0 y=15.0, w=10.23, b=2.60, dloss/dw=-4.3, dloss/db=-4.3
	 x=2.0 y=25.0, w=10.27, b=2.65, dloss/dw=-7.3, dloss/db=-3.6
	 x=3.0 y=35.0, w=10.34, b=2.68, dloss/dw=-7.7, dloss/db=-2.6
	 x=4.0 y=45.0, w=10.42, b=2.71, dloss/dw=-4.9, dloss/db=-1.2
	 x=5.0 y=55.0, w=10.47, b=2.72, dloss/dw=0.6, dloss/db=0.1
	 x=6.0 y=65.0, w=10.46, b=2.72, dlos

	 x=5.0 y=55.0, w=10.03, b=4.87, dloss/dw=0.0, dloss/db=0.0
	 x=6.0 y=65.0, w=10.03, b=4.87, dloss/dw=0.3, dloss/db=0.1
	 x=7.0 y=75.0, w=10.02, b=4.87, dloss/dw=0.4, dloss/db=0.1
	 x=8.0 y=85.0, w=10.02, b=4.87, dloss/dw=0.3, dloss/db=0.0
	 x=9.0 y=95.0, w=10.02, b=4.87, dloss/dw=0.2, dloss/db=0.0
	 x=10.0 y=105.0, w=10.01, b=4.87, dloss/dw=0.1, dloss/db=0.0
Loss at epoch #83: 0.000055 

	 x=1.0 y=15.0, w=10.01, b=4.87, dloss/dw=-0.2, dloss/db=-0.2
	 x=2.0 y=25.0, w=10.01, b=4.87, dloss/dw=-0.4, dloss/db=-0.2
	 x=3.0 y=35.0, w=10.02, b=4.87, dloss/dw=-0.4, dloss/db=-0.1
	 x=4.0 y=45.0, w=10.02, b=4.87, dloss/dw=-0.3, dloss/db=-0.1
	 x=5.0 y=55.0, w=10.03, b=4.87, dloss/dw=0.0, dloss/db=0.0
	 x=6.0 y=65.0, w=10.03, b=4.87, dloss/dw=0.3, dloss/db=0.1
	 x=7.0 y=75.0, w=10.02, b=4.87, dloss/dw=0.4, dloss/db=0.1
	 x=8.0 y=85.0, w=10.02, b=4.87, dloss/dw=0.3, dloss/db=0.0
	 x=9.0 y=95.0, w=10.02, b=4.87, dloss/dw=0.2, dloss/db=0.0
	 x=10.0 y=105.0, w=10.01, b=4.87, dloss/dw=0.1, dloss/db=0.


Optional: NN with tensor and autograd
-------------------------------

We consider a fully-connected ReLU network with one hidden layer and no biases, trained to predict y from x using Euclidean error.

The model that we want to build has the following structure:
$$\hat{y}(x) = \text{relu}(x.w_1).w_2,$$
where $x$ and $y$ are the input and output features (of dimension 1000 and 10, respectively). Here the relu activation function is used and $w_1$ and $w_2$ are weight matrices.

This implementation computes the forward pass using operations on PyTorch Tensors, and uses PyTorch autograd to compute gradients.


In [ ]:
%matplotlib inline

import torch

dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold input and outputs.
# Setting requires_grad=False indicates that we do not need to compute gradients
# with respect to these Tensors during the backward pass.
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# Create random Tensors for weights.
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y using operations on Tensors; these
    # are exactly the same operations we used to compute the forward pass using
    # Tensors, but we do not need to keep references to intermediate values since
    # we are not implementing the backward pass by hand.
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    
    # alternativelt you can use the built-in pytorch relu function
    # y_pred = torch.relu(x.mm(w1)).mm(w2)

    # Compute and print loss using operations on Tensors.
    # Now loss is a Tensor of shape (1,)
    # loss.item() gets the a scalar value held in the loss.
    loss = (y_pred - y).pow(2).sum()
    print(t, loss.item())

    # Use autograd to compute the backward pass. This call will compute the
    # gradient of loss with respect to all Tensors with requires_grad=True.
    # After this call w1.grad and w2.grad will be Tensors holding the gradient
    # of the loss with respect to w1 and w2 respectively.
    loss.backward()

    # Manually update weights using gradient descent. Wrap in torch.no_grad()
    # because weights have requires_grad=True, but we don't need to track this
    # in autograd.
    # An alternative way is to operate on weight.data and weight.grad.data.
    # Recall that tensor.data gives a tensor that shares the storage with
    # tensor, but doesn't track history.
    # You can also use torch.optim.SGD to achieve this.
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad

        # Manually zero the gradients after updating weights
        w1.grad.zero_()
        w2.grad.zero_()

### Exercice
Add one more hidden layer with 100 neurons. Use successively sigmoid (torch.sigmoid) and relu (torch.relu) activation functions.

Note: you might need to increase the numbers of epochs (this solution is much less effective than the previous one !)


In [30]:
import numpy as np

%matplotlib inline

import torch

dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H1, H2, D_out = 64, 1000, 100, 100, 10

# Create random Tensors to hold input and outputs.
# Setting requires_grad=False indicates that we do not need to compute gradients
# with respect to these Tensors during the backward pass.
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# Create random Tensors for weights.
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
w1 = torch.randn(D_in, H1, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H1, H2, device=device, dtype=dtype, requires_grad=True)
w3 = torch.randn(H2, D_out, device=device, dtype=dtype, requires_grad=True)

learning_rate = 1e-6
for t in range(10000):
    
    # y_pred with sigmoid activation function
    y_pred = torch.relu(torch.sigmoid(x.mm(w1)).mm(w2)).mm(w3)
    
    #y_pred = x.mm(w1).clamp(min=0).mm(w2).clamp(min=0).mm(w3)
        
    # Compute and print loss using operations on Tensors.
    # Now loss is a Tensor of shape (1,)
    # loss.item() gets the a scalar value held in the loss.
    loss = (y_pred - y).pow(2).sum()
    print(t, loss.item())
    
    # Use autograd to compute the backward pass. This call will compute the
    # gradient of loss with respect to all Tensors with requires_grad=True.
    # After this call w1.grad and w2.grad will be Tensors holding the gradient
    # of the loss with respect to w1 and w2 respectively.
    loss.backward()

    # Manually update weights using gradient descent. Wrap in torch.no_grad()
    # because weights have requires_grad=True, but we don't need to track this
    # in autograd.
    # An alternative way is to operate on weight.data and weight.grad.data.
    # Recall that tensor.data gives a tensor that shares the storage with
    # tensor, but doesn't track history.
    # You can also use torch.optim.SGD to achieve this.
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        w3 -= learning_rate * w3.grad

        # Manually zero the gradients after updating weights
        w1.grad.zero_()
        w2.grad.zero_()
        w3.grad.zero_()

0 1179604.5
1 868468.5625
2 696925.25
3 592580.625
4 524517.3125
5 477580.28125
6 442786.125
7 415417.5625
8 392899.84375
9 373899.15625
10 357373.09375
11 343139.96875
12 330850.90625
13 319962.21875
14 310181.3125
15 301274.875
16 293071.46875
17 285374.5
18 278217.625
19 271477.71875
20 265055.59375
21 258905.28125
22 253058.515625
23 247456.53125
24 242098.4375
25 236934.171875
26 231957.921875
27 227161.890625
28 222582.4375
29 218207.28125
30 213994.921875
31 209888.21875
32 205889.609375
33 201961.0625
34 198125.765625
35 194370.875
36 190744.96875
37 187161.5
38 183700.53125
39 180380.421875
40 177165.890625
41 174000.265625
42 170909.734375
43 167875.71875
44 164900.875
45 162009.09375
46 159214.390625
47 156504.984375
48 153889.796875
49 151356.078125
50 148930.359375
51 146606.46875
52 144348.3125
53 142159.59375
54 140042.03125
55 137979.921875
56 135975.15625
57 133996.59375
58 132045.734375
59 130139.1484375
60 128262.7890625
61 126429.4765625
62 124632.796875
63 122863.0

499 8372.4169921875
500 8342.6298828125
501 8313.0146484375
502 8283.6298828125
503 8254.1640625
504 8224.9599609375
505 8196.0908203125
506 8167.263671875
507 8138.42724609375
508 8109.91845703125
509 8081.501953125
510 8053.04736328125
511 8024.99658203125
512 7996.84912109375
513 7968.98583984375
514 7941.08203125
515 7913.576171875
516 7886.0849609375
517 7858.36376953125
518 7831.4326171875
519 7804.017578125
520 7777.111328125
521 7750.404296875
522 7723.27978515625
523 7696.623046875
524 7669.93017578125
525 7643.3125
526 7616.98486328125
527 7590.44580078125
528 7564.47900390625
529 7538.51708984375
530 7512.38818359375
531 7486.58984375
532 7461.08349609375
533 7435.29443359375
534 7410.15625
535 7385.01123046875
536 7359.56396484375
537 7334.77734375
538 7309.73193359375
539 7285.12841796875
540 7260.60205078125
541 7235.77978515625
542 7211.630859375
543 7187.16015625
544 7162.9091796875
545 7139.14599609375
546 7114.8037109375
547 7090.81494140625
548 7067.37841796875
549 7

986 1995.93798828125
987 1990.94921875
988 1986.113037109375
989 1981.344482421875
990 1976.39404296875
991 1971.6051025390625
992 1966.89013671875
993 1961.9984130859375
994 1957.2294921875
995 1952.577880859375
996 1947.7669677734375
997 1943.0308837890625
998 1938.3643798828125
999 1933.662841796875
1000 1928.947509765625
1001 1924.3109130859375
1002 1919.6588134765625
1003 1915.0062255859375
1004 1910.39697265625
1005 1905.8446044921875
1006 1901.185791015625
1007 1896.6170654296875
1008 1892.139404296875
1009 1887.550537109375
1010 1882.9356689453125
1011 1878.4775390625
1012 1874.011474609375
1013 1869.4068603515625
1014 1864.9345703125
1015 1860.508056640625
1016 1855.9384765625
1017 1851.4925537109375
1018 1847.0765380859375
1019 1842.5904541015625
1020 1838.1798095703125
1021 1833.8402099609375
1022 1829.427490234375
1023 1824.9986572265625
1024 1820.6846923828125
1025 1816.2718505859375
1026 1812.0079345703125
1027 1807.657470703125
1028 1803.3048095703125
1029 1799.060302734

1458 734.6864013671875
1459 733.3159790039062
1460 731.9485473632812
1461 730.59130859375
1462 729.2036743164062
1463 727.89501953125
1464 726.4913940429688
1465 725.1429443359375
1466 723.7950439453125
1467 722.4912109375
1468 721.1082763671875
1469 719.7607421875
1470 718.4508056640625
1471 717.1024780273438
1472 715.766845703125
1473 714.4319458007812
1474 713.1456298828125
1475 711.798583984375
1476 710.4876708984375
1477 709.1569213867188
1478 707.8533325195312
1479 706.536865234375
1480 705.2332153320312
1481 703.9149169921875
1482 702.59130859375
1483 701.2750244140625
1484 699.9557495117188
1485 698.6556396484375
1486 697.3757934570312
1487 696.0677490234375
1488 694.7366943359375
1489 693.5140380859375
1490 692.1900634765625
1491 690.9382934570312
1492 689.5879516601562
1493 688.4011840820312
1494 687.0679321289062
1495 685.7921142578125
1496 684.5494384765625
1497 683.2601928710938
1498 682.052001953125
1499 680.7426147460938
1500 679.482177734375
1501 678.2407836914062
1502 

1821 386.8207702636719
1822 386.1727600097656
1823 385.5055236816406
1824 384.8625183105469
1825 384.2398376464844
1826 383.57379150390625
1827 382.9405822753906
1828 382.3013916015625
1829 381.6544189453125
1830 381.0196228027344
1831 380.3813781738281
1832 379.7278747558594
1833 379.1108093261719
1834 378.4823303222656
1835 377.8381042480469
1836 377.2090148925781
1837 376.56890869140625
1838 375.9527893066406
1839 375.3274230957031
1840 374.6815490722656
1841 374.0712890625
1842 373.4711608886719
1843 372.8155517578125
1844 372.19927978515625
1845 371.5690002441406
1846 370.9700012207031
1847 370.3448486328125
1848 369.7196044921875
1849 369.1163024902344
1850 368.50933837890625
1851 367.8828125
1852 367.26824951171875
1853 366.6698303222656
1854 366.0450134277344
1855 365.4556884765625
1856 364.8363342285156
1857 364.22161865234375
1858 363.62872314453125
1859 363.0318908691406
1860 362.41455078125
1861 361.8207702636719
1862 361.2138977050781
1863 360.626220703125
1864 360.0377197

2222 204.45278930664062
2223 204.1374053955078
2224 203.82850646972656
2225 203.52444458007812
2226 203.21078491210938
2227 202.903564453125
2228 202.60101318359375
2229 202.29901123046875
2230 201.98855590820312
2231 201.6769561767578
2232 201.38804626464844
2233 201.0823211669922
2234 200.76605224609375
2235 200.46286010742188
2236 200.16761779785156
2237 199.867919921875
2238 199.56124877929688
2239 199.2545166015625
2240 198.96731567382812
2241 198.66104125976562
2242 198.3649444580078
2243 198.05615234375
2244 197.76611328125
2245 197.4655303955078
2246 197.16519165039062
2247 196.86891174316406
2248 196.5816650390625
2249 196.28414916992188
2250 195.97886657714844
2251 195.68368530273438
2252 195.39601135253906
2253 195.0997314453125
2254 194.81439208984375
2255 194.5126953125
2256 194.21897888183594
2257 193.92990112304688
2258 193.6494140625
2259 193.3455352783203
2260 193.05482482910156
2261 192.7706756591797
2262 192.4833984375
2263 192.19168090820312
2264 191.89572143554688


2739 97.1827392578125
2740 97.05094909667969
2741 96.92007446289062
2742 96.78543853759766
2743 96.65357208251953
2744 96.51910400390625
2745 96.39087677001953
2746 96.25691986083984
2747 96.1240005493164
2748 95.99235534667969
2749 95.86006164550781
2750 95.72847747802734
2751 95.5985336303711
2752 95.47090911865234
2753 95.34072875976562
2754 95.20767974853516
2755 95.0758056640625
2756 94.94480895996094
2757 94.8169937133789
2758 94.68950653076172
2759 94.55841827392578
2760 94.43123626708984
2761 94.2998046875
2762 94.17362976074219
2763 94.04499053955078
2764 93.91475677490234
2765 93.78365325927734
2766 93.65937805175781
2767 93.52970123291016
2768 93.40916442871094
2769 93.27486419677734
2770 93.15010833740234
2771 93.02139282226562
2772 92.89741516113281
2773 92.7689437866211
2774 92.63904571533203
2775 92.51568603515625
2776 92.38890838623047
2777 92.26480865478516
2778 92.1388931274414
2779 92.01199340820312
2780 91.88787841796875
2781 91.76004028320312
2782 91.6371078491211


3109 59.34525680541992
3110 59.26773452758789
3111 59.192054748535156
3112 59.11667251586914
3113 59.03973388671875
3114 58.96141052246094
3115 58.887184143066406
3116 58.80896759033203
3117 58.73186111450195
3118 58.65692901611328
3119 58.58171844482422
3120 58.50497817993164
3121 58.43073272705078
3122 58.35456848144531
3123 58.2781867980957
3124 58.20379638671875
3125 58.12912368774414
3126 58.05295181274414
3127 57.97728729248047
3128 57.901268005371094
3129 57.828590393066406
3130 57.75347137451172
3131 57.680240631103516
3132 57.605106353759766
3133 57.52906799316406
3134 57.45458221435547
3135 57.38359451293945
3136 57.3069953918457
3137 57.233882904052734
3138 57.1590690612793
3139 57.085548400878906
3140 57.011138916015625
3141 56.93946075439453
3142 56.866615295410156
3143 56.79322052001953
3144 56.717063903808594
3145 56.64677810668945
3146 56.573150634765625
3147 56.50068283081055
3148 56.42515182495117
3149 56.354644775390625
3150 56.279273986816406
3151 56.20921325683594


3618 31.308387756347656
3619 31.270282745361328
3620 31.23213005065918
3621 31.193634033203125
3622 31.156103134155273
3623 31.11733055114746
3624 31.080333709716797
3625 31.042293548583984
3626 31.004487991333008
3627 30.96585464477539
3628 30.92839813232422
3629 30.89066505432129
3630 30.852895736694336
3631 30.814485549926758
3632 30.777801513671875
3633 30.7403507232666
3634 30.702381134033203
3635 30.664979934692383
3636 30.627120971679688
3637 30.590614318847656
3638 30.553478240966797
3639 30.516128540039062
3640 30.47834014892578
3641 30.441444396972656
3642 30.404388427734375
3643 30.36703109741211
3644 30.3301944732666
3645 30.294553756713867
3646 30.257280349731445
3647 30.219562530517578
3648 30.183265686035156
3649 30.1464786529541
3650 30.10913848876953
3651 30.071794509887695
3652 30.035839080810547
3653 29.99867057800293
3654 29.963665008544922
3655 29.927173614501953
3656 29.889894485473633
3657 29.853878021240234
3658 29.81722640991211
3659 29.7812557220459
3660 29.74

4111 17.321046829223633
4112 17.301143646240234
4113 17.280065536499023
4114 17.25959014892578
4115 17.239492416381836
4116 17.218734741210938
4117 17.198930740356445
4118 17.178510665893555
4119 17.158151626586914
4120 17.137781143188477
4121 17.117956161499023
4122 17.0969295501709
4123 17.07727813720703
4124 17.057273864746094
4125 17.037029266357422
4126 17.017017364501953
4127 16.99687385559082
4128 16.97704315185547
4129 16.95606803894043
4130 16.93695831298828
4131 16.916810989379883
4132 16.896686553955078
4133 16.876855850219727
4134 16.85687255859375
4135 16.836875915527344
4136 16.81679916381836
4137 16.797325134277344
4138 16.77715301513672
4139 16.75779914855957
4140 16.737974166870117
4141 16.717864990234375
4142 16.698740005493164
4143 16.678735733032227
4144 16.658946990966797
4145 16.639188766479492
4146 16.6203670501709
4147 16.600261688232422
4148 16.580707550048828
4149 16.561403274536133
4150 16.541622161865234
4151 16.522003173828125
4152 16.50240135192871
4153 16

4473 11.34156322479248
4474 11.328559875488281
4475 11.31551456451416
4476 11.30213737487793
4477 11.289274215698242
4478 11.276030540466309
4479 11.263300895690918
4480 11.250367164611816
4481 11.237238883972168
4482 11.224124908447266
4483 11.211287498474121
4484 11.198310852050781
4485 11.185050010681152
4486 11.172497749328613
4487 11.159527778625488
4488 11.146697044372559
4489 11.13368034362793
4490 11.121213912963867
4491 11.10779857635498
4492 11.095096588134766
4493 11.082354545593262
4494 11.069734573364258
4495 11.05676555633545
4496 11.044079780578613
4497 11.031665802001953
4498 11.018440246582031
4499 11.00592041015625
4500 10.993060111999512
4501 10.980388641357422
4502 10.967889785766602
4503 10.955188751220703
4504 10.942512512207031
4505 10.929889678955078
4506 10.917202949523926
4507 10.904620170593262
4508 10.892244338989258
4509 10.879454612731934
4510 10.86694622039795
4511 10.85465145111084
4512 10.84176254272461
4513 10.829316139221191
4514 10.81692123413086
451

5009 6.1581645011901855
5010 6.151173114776611
5011 6.144355297088623
5012 6.137485027313232
5013 6.130620002746582
5014 6.123692989349365
5015 6.116810321807861
5016 6.110016822814941
5017 6.103051662445068
5018 6.096430778503418
5019 6.089412212371826
5020 6.082726955413818
5021 6.075723171234131
5022 6.069002628326416
5023 6.062241554260254
5024 6.055246829986572
5025 6.048699378967285
5026 6.041879653930664
5027 6.035218715667725
5028 6.028280258178711
5029 6.021705150604248
5030 6.014791011810303
5031 6.007978439331055
5032 6.001269817352295
5033 5.994688034057617
5034 5.987870216369629
5035 5.981131076812744
5036 5.974630832672119
5037 5.967730522155762
5038 5.961108207702637
5039 5.954369068145752
5040 5.947822570800781
5041 5.941137790679932
5042 5.934427261352539
5043 5.927835464477539
5044 5.921144008636475
5045 5.914477348327637
5046 5.907934665679932
5047 5.9013895988464355
5048 5.894626140594482
5049 5.888175964355469
5050 5.881528377532959
5051 5.874966621398926
5052 5.86

5506 3.547982692718506
5507 3.5440492630004883
5508 3.5401954650878906
5509 3.5363314151763916
5510 3.532423257827759
5511 3.5285136699676514
5512 3.5247297286987305
5513 3.5208444595336914
5514 3.5169835090637207
5515 3.5130228996276855
5516 3.5092973709106445
5517 3.505376100540161
5518 3.501540422439575
5519 3.497713804244995
5520 3.4938912391662598
5521 3.490149974822998
5522 3.486205816268921
5523 3.482459306716919
5524 3.478597402572632
5525 3.474780797958374
5526 3.470956802368164
5527 3.4671192169189453
5528 3.4634461402893066
5529 3.459531545639038
5530 3.455733060836792
5531 3.4520280361175537
5532 3.44821834564209
5533 3.4444217681884766
5534 3.4406089782714844
5535 3.4369165897369385
5536 3.433176279067993
5537 3.429365873336792
5538 3.425619125366211
5539 3.421874523162842
5540 3.418118476867676
5541 3.414294481277466
5542 3.4106040000915527
5543 3.406904697418213
5544 3.4031753540039062
5545 3.399412155151367
5546 3.395646333694458
5547 3.392047882080078
5548 3.3882398605

5999 2.0764713287353516
6000 2.0742955207824707
6001 2.072023391723633
6002 2.0698113441467285
6003 2.0675411224365234
6004 2.065343141555786
6005 2.063091993331909
6006 2.0608654022216797
6007 2.0586836338043213
6008 2.05647349357605
6009 2.054280996322632
6010 2.052051305770874
6011 2.04984188079834
6012 2.047637462615967
6013 2.0453948974609375
6014 2.043189287185669
6015 2.041015386581421
6016 2.038825035095215
6017 2.036665916442871
6018 2.0344269275665283
6019 2.0322418212890625
6020 2.0300917625427246
6021 2.0279347896575928
6022 2.02569580078125
6023 2.023519277572632
6024 2.0213146209716797
6025 2.0192370414733887
6026 2.016979217529297
6027 2.0148568153381348
6028 2.0126543045043945
6029 2.0105197429656982
6030 2.0083398818969727
6031 2.006159782409668
6032 2.0040266513824463
6033 2.001922845840454
6034 1.9997062683105469
6035 1.9975662231445312
6036 1.9953815937042236
6037 1.9932732582092285
6038 1.991179347038269
6039 1.9889572858810425
6040 1.986857295036316
6041 1.9847333

6423 1.3204963207244873
6424 1.319087266921997
6425 1.3176863193511963
6426 1.3162857294082642
6427 1.3149149417877197
6428 1.3134804964065552
6429 1.312092900276184
6430 1.310735821723938
6431 1.3093498945236206
6432 1.3079640865325928
6433 1.3065603971481323
6434 1.3052030801773071
6435 1.3038159608840942
6436 1.3023964166641235
6437 1.3010518550872803
6438 1.2996490001678467
6439 1.2982968091964722
6440 1.2969379425048828
6441 1.2955325841903687
6442 1.2941622734069824
6443 1.2927912473678589
6444 1.2914412021636963
6445 1.290046215057373
6446 1.2887016534805298
6447 1.2873387336730957
6448 1.2859764099121094
6449 1.2846081256866455
6450 1.2832533121109009
6451 1.2818702459335327
6452 1.2805442810058594
6453 1.279191255569458
6454 1.2778047323226929
6455 1.2764841318130493
6456 1.2751243114471436
6457 1.2738006114959717
6458 1.2724360227584839
6459 1.2710660696029663
6460 1.2697447538375854
6461 1.2683794498443604
6462 1.267045259475708
6463 1.265756607055664
6464 1.264404296875
646

6904 0.7968447208404541
6905 0.7960342168807983
6906 0.7952112555503845
6907 0.79438316822052
6908 0.793539822101593
6909 0.792735755443573
6910 0.7918932437896729
6911 0.7911134958267212
6912 0.7902445197105408
6913 0.7894276976585388
6914 0.7886170744895935
6915 0.7878058552742004
6916 0.7869672179222107
6917 0.786174476146698
6918 0.7853375673294067
6919 0.7845219969749451
6920 0.7837071418762207
6921 0.7829042077064514
6922 0.7821082472801208
6923 0.7812761068344116
6924 0.7804657220840454
6925 0.7796627879142761
6926 0.7788541316986084
6927 0.7780323624610901
6928 0.7772313952445984
6929 0.7764272093772888
6930 0.7756242752075195
6931 0.7748276591300964
6932 0.7740123271942139
6933 0.773232638835907
6934 0.7724012136459351
6935 0.7716341018676758
6936 0.7708120346069336
6937 0.770014762878418
6938 0.7692110538482666
6939 0.76842200756073
6940 0.7676157355308533
6941 0.7668490409851074
6942 0.7660351991653442
6943 0.765232264995575
6944 0.7644358277320862
6945 0.7636460065841675
69

7249 0.5580286383628845
7250 0.5574733018875122
7251 0.5568929314613342
7252 0.5563238263130188
7253 0.555759072303772
7254 0.5551891326904297
7255 0.5546074509620667
7256 0.5540363788604736
7257 0.5534588694572449
7258 0.5529124140739441
7259 0.5523481369018555
7260 0.5517792105674744
7261 0.5512028932571411
7262 0.550667405128479
7263 0.550083577632904
7264 0.5495120882987976
7265 0.5489545464515686
7266 0.54838627576828
7267 0.5478355288505554
7268 0.5472704768180847
7269 0.5467169880867004
7270 0.5461525321006775
7271 0.5455897450447083
7272 0.5450303554534912
7273 0.5444759726524353
7274 0.5439210534095764
7275 0.5433611273765564
7276 0.5427863597869873
7277 0.542244017124176
7278 0.5417054295539856
7279 0.5411341786384583
7280 0.540573239326477
7281 0.5400198698043823
7282 0.5394759178161621
7283 0.5389323830604553
7284 0.5383707880973816
7285 0.5378246307373047
7286 0.5372587442398071
7287 0.5367176532745361
7288 0.536180317401886
7289 0.5356301069259644
7290 0.5350682735443115


7740 0.3387509882450104
7741 0.33840322494506836
7742 0.33806413412094116
7743 0.33772674202919006
7744 0.33739203214645386
7745 0.3370484709739685
7746 0.33671116828918457
7747 0.33637043833732605
7748 0.3360282778739929
7749 0.3356950581073761
7750 0.3353571891784668
7751 0.3350168466567993
7752 0.3346790373325348
7753 0.33433419466018677
7754 0.33401501178741455
7755 0.3336728811264038
7756 0.3333357572555542
7757 0.33299627900123596
7758 0.33266350626945496
7759 0.332329124212265
7760 0.331998348236084
7761 0.3316606879234314
7762 0.3313365578651428
7763 0.3309916853904724
7764 0.3306664824485779
7765 0.33032554388046265
7766 0.33000850677490234
7767 0.3296746611595154
7768 0.3293411433696747
7769 0.32899919152259827
7770 0.32868146896362305
7771 0.32835137844085693
7772 0.3280090093612671
7773 0.3276911675930023
7774 0.32735729217529297
7775 0.3270300626754761
7776 0.32669565081596375
7777 0.3263784646987915
7778 0.32605013251304626
7779 0.3257174491882324
7780 0.3253825604915619


8176 0.2193627506494522
8177 0.21913909912109375
8178 0.218928724527359
8179 0.21871623396873474
8180 0.21849828958511353
8181 0.2182803452014923
8182 0.2180626541376114
8183 0.21784844994544983
8184 0.2176332324743271
8185 0.21742458641529083
8186 0.2172187715768814
8187 0.21698780357837677
8188 0.21677687764167786
8189 0.21656814217567444
8190 0.2163560539484024
8191 0.21613620221614838
8192 0.2159225046634674
8193 0.21571145951747894
8194 0.21550098061561584
8195 0.2152813971042633
8196 0.21507036685943604
8197 0.2148621678352356
8198 0.21464748680591583
8199 0.2144359052181244
8200 0.21421723067760468
8201 0.21401430666446686
8202 0.21381106972694397
8203 0.21359306573867798
8204 0.21337947249412537
8205 0.21316993236541748
8206 0.21296115219593048
8207 0.212748721241951
8208 0.2125357687473297
8209 0.21233248710632324
8210 0.21212930977344513
8211 0.21191620826721191
8212 0.2117040604352951
8213 0.2114984393119812
8214 0.2112933099269867
8215 0.21108223497867584
8216 0.21087303757

8531 0.15498782694339752
8532 0.15483233332633972
8533 0.15468768775463104
8534 0.15453705191612244
8535 0.15438255667686462
8536 0.1542372852563858
8537 0.15408901870250702
8538 0.15394404530525208
8539 0.15379048883914948
8540 0.15364104509353638
8541 0.1534925103187561
8542 0.15333864092826843
8543 0.15319249033927917
8544 0.15304234623908997
8545 0.15289583802223206
8546 0.152747243642807
8547 0.15260441601276398
8548 0.1524527668952942
8549 0.15230512619018555
8550 0.15216079354286194
8551 0.1520104855298996
8552 0.15186621248722076
8553 0.15171608328819275
8554 0.15157273411750793
8555 0.1514255702495575
8556 0.1512763798236847
8557 0.15112918615341187
8558 0.1509835124015808
8559 0.15084093809127808
8560 0.15069857239723206
8561 0.15054981410503387
8562 0.1504005491733551
8563 0.1502586305141449
8564 0.15011316537857056
8565 0.14996951818466187
8566 0.14982493221759796
8567 0.14967457950115204
8568 0.14952819049358368
8569 0.14938637614250183
8570 0.14924731850624084
8571 0.1491

8890 0.10981110483407974
8891 0.10970360785722733
8892 0.1095973327755928
8893 0.1094917580485344
8894 0.10939531028270721
8895 0.10928906500339508
8896 0.10918129980564117
8897 0.1090829074382782
8898 0.10897856205701828
8899 0.10887853056192398
8900 0.10877176374197006
8901 0.10866829752922058
8902 0.108566515147686
8903 0.10846593230962753
8904 0.1083575189113617
8905 0.10825662314891815
8906 0.10815403610467911
8907 0.1080533042550087
8908 0.10795662552118301
8909 0.10785014927387238
8910 0.10774806886911392
8911 0.10764190554618835
8912 0.10753767937421799
8913 0.10743821412324905
8914 0.107339046895504
8915 0.10723507404327393
8916 0.10713718086481094
8917 0.1070338785648346
8918 0.10693075507879257
8919 0.1068304106593132
8920 0.1067313626408577
8921 0.10663267225027084
8922 0.10652634501457214
8923 0.10642481595277786
8924 0.10632575303316116
8925 0.10622779279947281
8926 0.10612469911575317
8927 0.10602236539125443
8928 0.1059233546257019
8929 0.10582268983125687
8930 0.105721

9257 0.07770123332738876
9258 0.07763078063726425
9259 0.07755821943283081
9260 0.0774819478392601
9261 0.07741087675094604
9262 0.0773385688662529
9263 0.07726603746414185
9264 0.07719241082668304
9265 0.07712587714195251
9266 0.07705213129520416
9267 0.07697756588459015
9268 0.07690560817718506
9269 0.07683730125427246
9270 0.0767614096403122
9271 0.07669451832771301
9272 0.07662124931812286
9273 0.07654732465744019
9274 0.07647763937711716
9275 0.07640215754508972
9276 0.07633639872074127
9277 0.07626304030418396
9278 0.07619192451238632
9279 0.07612226158380508
9280 0.07604895532131195
9281 0.07597611099481583
9282 0.07590833306312561
9283 0.07583871483802795
9284 0.07576635479927063
9285 0.07569620758295059
9286 0.07562433928251266
9287 0.07555776089429855
9288 0.07548252493143082
9289 0.07541266083717346
9290 0.07534332573413849
9291 0.07527388632297516
9292 0.07520178705453873
9293 0.0751328244805336
9294 0.07506340742111206
9295 0.07499450445175171
9296 0.07492520660161972
9297

9729 0.05028105154633522
9730 0.050234366208314896
9731 0.05018993467092514
9732 0.05014156550168991
9733 0.05009732395410538
9734 0.05005078390240669
9735 0.050006527453660965
9736 0.04996262118220329
9737 0.04991772398352623
9738 0.04987187683582306
9739 0.04982822388410568
9740 0.049782682210206985
9741 0.049736976623535156
9742 0.04969368875026703
9743 0.04964691027998924
9744 0.049602579325437546
9745 0.049556173384189606
9746 0.04951251298189163
9747 0.049467120319604874
9748 0.04941993206739426
9749 0.04937761276960373
9750 0.04933146759867668
9751 0.04928704723715782
9752 0.049243658781051636
9753 0.049199074506759644
9754 0.04915500804781914
9755 0.04910978674888611
9756 0.04906630888581276
9757 0.04902121052145958
9758 0.04897726699709892
9759 0.048934437334537506
9760 0.04888924956321716
9761 0.04884542524814606
9762 0.048801254481077194
9763 0.048756349831819534
9764 0.0487101711332798
9765 0.0486680343747139
9766 0.04862498492002487
9767 0.04858234152197838
9768 0.04853723