## Using PyTorch Tensors 

A PyTorch Tensor is basically the same as a numpy multidimensional array: it does not know
anything about deep learning or computational graphs or gradients, and is just
a generic n-dimensional array to be used for arbitrary numeric computation.

The biggest difference between a numpy array and a PyTorch Tensor is that
a PyTorch Tensor can run on either CPU or GPU. To run operations on the GPU,
just cast the Tensor to a cuda datatype.

(This example is adapted from: https://pytorch.org/tutorials/beginner/pytorch_with_examples.html )

### Basic tensor matrix operations

In [1]:
import torch

# Simple matrix
m1 = torch.ones(3, 4)
print('Matrix m1: \n', m1)
print(m1.shape,"\n")

# Another (random) matrix
m2 = torch.rand(3, 4) # fill 3x4 matrix with uniform random numbers in [0,1] interval
print('Matrix m2: \n', m2)
print(m2.shape,"\n")

# Transpose of a matrix
print('Matrix m2^T: \n', m2.t())
print(m2.t().shape,"\n")

# Matrix operations
m3 = m1*m2      # Not a matrix multiplication ! Here each value in matrix m1 are multiplied by value m2
print('Matrix m3: \n', m3)
print(m3.shape,"\n")

# Matrix multiplication using torch.mm
m4 = m1.mm(m2.t())
print('Matrix m4: \n', m4)
print(m4.shape,"\n")

# Matrix multiplication using torch.matmul
m5 = m1.matmul(m2.t())
print('Matrix m5: \n', m5)
print(m5.shape,"\n")

# For matrix-vector multiplication there is also the possibility to use torch.mv
vec = torch.tensor([1.0,2.0,3.0])
print(torch.matmul(m5, vec))

Matrix m1: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([3, 4]) 

Matrix m2: 
 tensor([[0.1157, 0.4705, 0.1604, 0.6519],
        [0.5901, 0.3330, 0.9829, 0.5998],
        [0.5548, 0.0507, 0.7762, 0.8113]])
torch.Size([3, 4]) 

Matrix m2^T: 
 tensor([[0.1157, 0.5901, 0.5548],
        [0.4705, 0.3330, 0.0507],
        [0.1604, 0.9829, 0.7762],
        [0.6519, 0.5998, 0.8113]])
torch.Size([4, 3]) 

Matrix m3: 
 tensor([[0.1157, 0.4705, 0.1604, 0.6519],
        [0.5901, 0.3330, 0.9829, 0.5998],
        [0.5548, 0.0507, 0.7762, 0.8113]])
torch.Size([3, 4]) 

Matrix m4: 
 tensor([[1.3984, 2.5058, 2.1929],
        [1.3984, 2.5058, 2.1929],
        [1.3984, 2.5058, 2.1929]])
torch.Size([3, 3]) 

Matrix m5: 
 tensor([[1.3984, 2.5058, 2.1929],
        [1.3984, 2.5058, 2.1929],
        [1.3984, 2.5058, 2.1929]])
torch.Size([3, 3]) 

tensor([12.9888, 12.9888, 12.9888])


### More operations (power, sum, clamp, ...)

(See even more basic operations here: https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/)

In [2]:
mat = torch.rand(3, 4)
print(mat)

# Takes the power of each element in input
print(mat.pow(3))

# Returns the sum of all elements in the input tensor
print(mat.sum())

# Clamp all elements in input into the range [ min, max ] and return a resulting tensor
print(mat.clamp(0.3,0.7))

tensor([[0.3053, 0.3329, 0.1608, 0.3585],
        [0.2057, 0.0540, 0.3088, 0.3913],
        [0.1058, 0.3738, 0.0864, 0.2156]])
tensor([[0.0285, 0.0369, 0.0042, 0.0461],
        [0.0087, 0.0002, 0.0294, 0.0599],
        [0.0012, 0.0522, 0.0006, 0.0100]])
tensor(2.8989)
tensor([[0.3053, 0.3329, 0.3000, 0.3585],
        [0.3000, 0.3000, 0.3088, 0.3913],
        [0.3000, 0.3738, 0.3000, 0.3000]])


### Convertion to numpy array

In [3]:
import numpy as np

# convertion PyTorch -> numpy
a = torch.randn(5)
b = a.numpy()

# convertion numpy -> PyTorch
c = torch.from_numpy(b)

print(a)
print(b)
print(c)

tensor([-1.7202,  0.8410, -0.3200,  1.4264,  1.1526])
[-1.7201914   0.8410047  -0.32003662  1.42642     1.1526212 ]
tensor([-1.7202,  0.8410, -0.3200,  1.4264,  1.1526])


### Autograd

A PyTorch Tensor represents a node in a computational graph. If ``x`` is a
Tensor that has ``x.requires_grad=True`` then ``x.grad`` is another Tensor
holding the gradient of ``x`` with respect to some scalar value.

Example for simple regression (adapted from S. Sviridov lecture):

In [4]:
# Simple regression example
x = [1., 2., 3., 4., 5.]           # data
y = [10., 20., 30., 40., 50.]      # target values

# Gradients will be calculated w.r.t this tensors (has "requires_grad=True")
w = torch.tensor([1.],requires_grad=True)

# Number of loops on all sample
for epoch in range(5):
    
    # Loop on data events and target values
    for x_i, y_i in zip(x, y):
        
        # compute predicted target variable
        y_pred = x_i * w
                
        # compute Mean Squared Error (MSE)
        loss = (y_pred - y_i) ** 2
        
        # With PyTorch we can automatically compute the derivative of the loss 
        # w.r.t. the tensors that have requires_grad set to True (i.e. weights).
        # compute gradients
        loss.backward()
                        
        print('\t x=%.1f y=%.1f, w=%.2f, dloss/dw=%.1f' % (x_i, y_i, w.data, w.grad.data))
                
        # make one step towards the local minima, with learning rate 0.01
        w.data -= 0.01 * w.grad.data
        
        # clear gradients after updating weights
        w.grad.data.zero_()
        
    print('Loss at epoch #%d: %.6f \n' % (epoch+1, loss.data[0]))

print('Final: w = %.4f' % (w.data))


	 x=1.0 y=10.0, w=1.00, dloss/dw=-18.0
	 x=2.0 y=20.0, w=1.18, dloss/dw=-70.6
	 x=3.0 y=30.0, w=1.89, dloss/dw=-146.1
	 x=4.0 y=40.0, w=3.35, dloss/dw=-212.9
	 x=5.0 y=50.0, w=5.48, dloss/dw=-226.2
Loss at epoch #1: 511.797760 

	 x=1.0 y=10.0, w=7.74, dloss/dw=-4.5
	 x=2.0 y=20.0, w=7.78, dloss/dw=-17.7
	 x=3.0 y=30.0, w=7.96, dloss/dw=-36.7
	 x=4.0 y=40.0, w=8.33, dloss/dw=-53.5
	 x=5.0 y=50.0, w=8.86, dloss/dw=-56.9
Loss at epoch #2: 32.337894 

	 x=1.0 y=10.0, w=9.43, dloss/dw=-1.1
	 x=2.0 y=20.0, w=9.44, dloss/dw=-4.5
	 x=3.0 y=30.0, w=9.49, dloss/dw=-9.2
	 x=4.0 y=40.0, w=9.58, dloss/dw=-13.5
	 x=5.0 y=50.0, w=9.71, dloss/dw=-14.3
Loss at epoch #3: 2.043265 

	 x=1.0 y=10.0, w=9.86, dloss/dw=-0.3
	 x=2.0 y=20.0, w=9.86, dloss/dw=-1.1
	 x=3.0 y=30.0, w=9.87, dloss/dw=-2.3
	 x=4.0 y=40.0, w=9.89, dloss/dw=-3.4
	 x=5.0 y=50.0, w=9.93, dloss/dw=-3.6
Loss at epoch #4: 0.129104 

	 x=1.0 y=10.0, w=9.96, dloss/dw=-0.1
	 x=2.0 y=20.0, w=9.96, dloss/dw=-0.3
	 x=3.0 y=30.0, w=9.97, dloss/d

### Exercice
Now we have the following data. How should be modified the above code ? How many epochs are needed for convergence ?


In [6]:
# Now we have the following data. How should be modified the above code 
x = [1., 2., 3., 4., 5., 6., 7., 8., 9., 10.]           # data
y = [15., 25., 35., 45., 55., 65., 75., 85., 95., 105.] # target values

# Gradients will be calculated w.r.t these two tensors (have "requires_grad=True")
w = torch.tensor([1.],requires_grad=True)
b = torch.tensor([0.],requires_grad=True)

for epoch in range(100):
    
    for x_i, y_i in zip(x, y):
        
        # compute predicted target variable
        y_pred = x_i * w + b
                
        # compute Mean Squared Error (MSE)
        loss = (y_pred - y_i) ** 2
        
        # With PyTorch we can automatically compute the derivative of the loss 
        # w.r.t. the tensors that have requires_grad set to True (i.e. w and b).
        # compute gradients
        loss.backward()
                        
        print('\t x=%.1f y=%.1f, w=%.2f, b=%.2f, dloss/dw=%.1f, dloss/db=%.1f' % (x_i, y_i, w.data, b.data, w.grad.data, b.grad.data))
                
        # make one step towards the local minima, with learning rate 0.01
        w.data -= 0.01 * w.grad.data
        b.data -= 0.01 * b.grad.data
        
        # clear gradients after updating weights
        w.grad.data.zero_()
        b.grad.data.zero_()
        
    print('Loss at epoch #%d: %.6f \n' % (epoch+1, loss.data[0]))

print('Final: w = %.4f, b = %4f' % (w.data, b.data))


	 x=1.0 y=15.0, w=1.00, b=0.00, dloss/dw=-28.0, dloss/db=-28.0
	 x=2.0 y=25.0, w=1.28, b=0.28, dloss/dw=-88.6, dloss/db=-44.3
	 x=3.0 y=35.0, w=2.17, b=0.72, dloss/dw=-166.7, dloss/db=-55.6
	 x=4.0 y=45.0, w=3.83, b=1.28, dloss/dw=-227.1, dloss/db=-56.8
	 x=5.0 y=55.0, w=6.10, b=1.85, dloss/dw=-226.3, dloss/db=-45.3
	 x=6.0 y=65.0, w=8.37, b=2.30, dloss/dw=-150.0, dloss/db=-25.0
	 x=7.0 y=75.0, w=9.87, b=2.55, dloss/dw=-47.3, dloss/db=-6.8
	 x=8.0 y=85.0, w=10.34, b=2.62, dloss/dw=5.4, dloss/db=0.7
	 x=9.0 y=95.0, w=10.29, b=2.61, dloss/dw=3.3, dloss/db=0.4
	 x=10.0 y=105.0, w=10.25, b=2.61, dloss/dw=2.7, dloss/db=0.3
Loss at epoch #1: 0.018289 

	 x=1.0 y=15.0, w=10.23, b=2.60, dloss/dw=-4.3, dloss/db=-4.3
	 x=2.0 y=25.0, w=10.27, b=2.65, dloss/dw=-7.3, dloss/db=-3.6
	 x=3.0 y=35.0, w=10.34, b=2.68, dloss/dw=-7.7, dloss/db=-2.6
	 x=4.0 y=45.0, w=10.42, b=2.71, dloss/dw=-4.9, dloss/db=-1.2
	 x=5.0 y=55.0, w=10.47, b=2.72, dloss/dw=0.6, dloss/db=0.1
	 x=6.0 y=65.0, w=10.46, b=2.72, dlos

	 x=5.0 y=55.0, w=10.03, b=4.87, dloss/dw=0.0, dloss/db=0.0
	 x=6.0 y=65.0, w=10.03, b=4.87, dloss/dw=0.3, dloss/db=0.1
	 x=7.0 y=75.0, w=10.02, b=4.87, dloss/dw=0.4, dloss/db=0.1
	 x=8.0 y=85.0, w=10.02, b=4.87, dloss/dw=0.3, dloss/db=0.0
	 x=9.0 y=95.0, w=10.02, b=4.87, dloss/dw=0.2, dloss/db=0.0
	 x=10.0 y=105.0, w=10.01, b=4.87, dloss/dw=0.1, dloss/db=0.0
Loss at epoch #83: 0.000055 

	 x=1.0 y=15.0, w=10.01, b=4.87, dloss/dw=-0.2, dloss/db=-0.2
	 x=2.0 y=25.0, w=10.01, b=4.87, dloss/dw=-0.4, dloss/db=-0.2
	 x=3.0 y=35.0, w=10.02, b=4.87, dloss/dw=-0.4, dloss/db=-0.1
	 x=4.0 y=45.0, w=10.02, b=4.87, dloss/dw=-0.3, dloss/db=-0.1
	 x=5.0 y=55.0, w=10.03, b=4.87, dloss/dw=0.0, dloss/db=0.0
	 x=6.0 y=65.0, w=10.03, b=4.87, dloss/dw=0.3, dloss/db=0.1
	 x=7.0 y=75.0, w=10.02, b=4.87, dloss/dw=0.4, dloss/db=0.1
	 x=8.0 y=85.0, w=10.02, b=4.87, dloss/dw=0.3, dloss/db=0.0
	 x=9.0 y=95.0, w=10.02, b=4.87, dloss/dw=0.2, dloss/db=0.0
	 x=10.0 y=105.0, w=10.01, b=4.87, dloss/dw=0.1, dloss/db=0.


NN with tensor and autograd
-------------------------------

We consider a fully-connected ReLU network with one hidden layer and no biases, trained to predict y from x using Euclidean error.

The model that we want to build has the following structure:
$$\hat{y}(x) = \text{relu}(x.w_1).w_2,$$
where $x$ and $y$ are the input and output features (of dimension 1000 and 10, respectively). Here the relu activation function is used and $w_1$ and $w_2$ are weight matrices.

The network consists of a fully-connected ReLU network with one hidden layer and no biases, trained to predict y from x by minimizing squared Euclidean distance.

This implementation computes the forward pass using operations on PyTorch Tensors, and uses PyTorch autograd to compute gradients.


In [1]:
%matplotlib inline

import torch

dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold input and outputs.
# Setting requires_grad=False indicates that we do not need to compute gradients
# with respect to these Tensors during the backward pass.
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# Create random Tensors for weights.
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y using operations on Tensors; these
    # are exactly the same operations we used to compute the forward pass using
    # Tensors, but we do not need to keep references to intermediate values since
    # we are not implementing the backward pass by hand.
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    
    # alternativelt you can use the built-in pytorch relu function
    # y_pred = torch.relu(x.mm(w1)).mm(w2)

    # Compute and print loss using operations on Tensors.
    # Now loss is a Tensor of shape (1,)
    # loss.item() gets the a scalar value held in the loss.
    loss = (y_pred - y).pow(2).sum()
    print(t, loss.item())

    # Use autograd to compute the backward pass. This call will compute the
    # gradient of loss with respect to all Tensors with requires_grad=True.
    # After this call w1.grad and w2.grad will be Tensors holding the gradient
    # of the loss with respect to w1 and w2 respectively.
    loss.backward()

    # Manually update weights using gradient descent. Wrap in torch.no_grad()
    # because weights have requires_grad=True, but we don't need to track this
    # in autograd.
    # An alternative way is to operate on weight.data and weight.grad.data.
    # Recall that tensor.data gives a tensor that shares the storage with
    # tensor, but doesn't track history.
    # You can also use torch.optim.SGD to achieve this.
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad

        # Manually zero the gradients after updating weights
        w1.grad.zero_()
        w2.grad.zero_()

0 30678590.0
1 25521168.0
2 23136452.0
3 20305556.0
4 16234543.0
5 11643255.0
6 7652273.0
7 4800460.5
8 3007879.75
9 1949954.25
10 1333952.5
11 967682.0625
12 739503.875
13 588779.375
14 482949.90625
15 404452.625
16 343662.75
17 294943.21875
18 255164.59375
19 222171.734375
20 194419.09375
21 170843.21875
22 150686.75
23 133354.125
24 118375.625
25 105375.421875
26 94043.390625
27 84146.6640625
28 75488.6015625
29 67864.171875
30 61132.984375
31 55179.12890625
32 49901.2109375
33 45205.5625
34 41021.734375
35 37282.4375
36 33935.19140625
37 30932.11328125
38 28231.67578125
39 25799.919921875
40 23605.1953125
41 21621.150390625
42 19825.15625
43 18196.712890625
44 16718.09375
45 15373.5673828125
46 14150.146484375
47 13035.361328125
48 12018.01171875
49 11088.7197265625
50 10239.16015625
51 9461.2841796875
52 8748.724609375
53 8094.9970703125
54 7495.0166015625
55 6943.86279296875
56 6437.087890625
57 5970.7197265625
58 5541.384765625
59 5145.693359375
60 4780.80322265625
61 4443.99609

453 8.810096187517047e-05
454 8.656635327497497e-05
455 8.475106005789712e-05
456 8.352175063919276e-05
457 8.235369750764221e-05
458 8.125367457978427e-05
459 7.997159264050424e-05
460 7.887403626227751e-05
461 7.721551082795486e-05
462 7.62003764975816e-05
463 7.511214062105864e-05
464 7.390701648546383e-05
465 7.257351535372436e-05
466 7.151535101002082e-05
467 7.078088674461469e-05
468 6.999324250500649e-05
469 6.884289177833125e-05
470 6.808150646975264e-05
471 6.700786616420373e-05
472 6.618237239308655e-05
473 6.498227594420314e-05
474 6.421494617825374e-05
475 6.33703893981874e-05
476 6.239462527446449e-05
477 6.163326179375872e-05
478 6.086544453864917e-05
479 6.017292616888881e-05
480 5.8904501202050596e-05
481 5.798885831609368e-05
482 5.715732186217792e-05
483 5.650144521496259e-05
484 5.598360439762473e-05
485 5.509749462362379e-05
486 5.459368185256608e-05
487 5.377618072088808e-05
488 5.293567664921284e-05
489 5.210505332797766e-05
490 5.152084122528322e-05
491 5.1013219

### Optional: Exercice
Add one more hidden layer with 100 neurons. Use successively sigmoid (torch.sigmoid) and relu (torch.relu) activation functions.

Note: you might need to increase the numbers of epochs (this solution is much less effective than the previous one !)


In [1]:
import numpy as np

%matplotlib inline

import torch

dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H1, H2, D_out = 64, 1000, 100, 100, 10

# Create random Tensors to hold input and outputs.
# Setting requires_grad=False indicates that we do not need to compute gradients
# with respect to these Tensors during the backward pass.
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# Create random Tensors for weights.
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
w1 = torch.randn(D_in, H1, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H1, H2, device=device, dtype=dtype, requires_grad=True)
w3 = torch.randn(H2, D_out, device=device, dtype=dtype, requires_grad=True)

learning_rate = 1e-6
for t in range(10000):
    
    # y_pred with sigmoid activation function
    y_pred = torch.relu(torch.sigmoid(x.mm(w1)).mm(w2)).mm(w3)
    
    #y_pred = x.mm(w1).clamp(min=0).mm(w2).clamp(min=0).mm(w3)
        
    # Compute and print loss using operations on Tensors.
    # Now loss is a Tensor of shape (1,)
    # loss.item() gets the a scalar value held in the loss.
    loss = (y_pred - y).pow(2).sum()
    print(t, loss.item())
    
    # Use autograd to compute the backward pass. This call will compute the
    # gradient of loss with respect to all Tensors with requires_grad=True.
    # After this call w1.grad and w2.grad will be Tensors holding the gradient
    # of the loss with respect to w1 and w2 respectively.
    loss.backward()

    # Manually update weights using gradient descent. Wrap in torch.no_grad()
    # because weights have requires_grad=True, but we don't need to track this
    # in autograd.
    # An alternative way is to operate on weight.data and weight.grad.data.
    # Recall that tensor.data gives a tensor that shares the storage with
    # tensor, but doesn't track history.
    # You can also use torch.optim.SGD to achieve this.
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        w3 -= learning_rate * w3.grad

        # Manually zero the gradients after updating weights
        w1.grad.zero_()
        w2.grad.zero_()
        w3.grad.zero_()

0 3103784.5
1 1282255.625
2 795089.5625
3 600897.1875
4 509082.4375
5 457848.9375
6 425294.40625
7 402190.46875
8 384108.71875
9 368774.34375
10 355053.03125
11 342778.40625
12 331371.5
13 320519.875
14 310609.75
15 301462.21875
16 292959.3125
17 284956.4375
18 277341.1875
19 270160.40625
20 263362.1875
21 256870.015625
22 250618.828125
23 244623.625
24 238913.859375
25 233407.46875
26 228145.390625
27 223097.171875
28 218154.09375
29 213378.78125
30 208779.90625
31 204435.71875
32 200293.8125
33 196321.265625
34 192465.046875
35 188824.625
36 185370.296875
37 182055.71875
38 178867.84375
39 175770.703125
40 172789.109375
41 169894.90625
42 167076.640625
43 164338.234375
44 161658.421875
45 159053.3125
46 156527.640625
47 154051.46875
48 151649.015625
49 149293.359375
50 147002.984375
51 144749.6875
52 142531.53125
53 140352.796875
54 138211.953125
55 136085.625
56 133968.578125
57 131877.375
58 129793.5078125
59 127764.8359375
60 125798.921875
61 123894.546875
62 122050.0625
63 120305

638 5187.11181640625
639 5171.03369140625
640 5155.255859375
641 5139.14404296875
642 5123.572265625
643 5107.58154296875
644 5092.03173828125
645 5076.30615234375
646 5060.845703125
647 5045.296875
648 5029.81982421875
649 5014.46533203125
650 4999.2197265625
651 4983.7880859375
652 4968.89013671875
653 4953.5478515625
654 4938.52783203125
655 4923.47802734375
656 4908.52734375
657 4893.6201171875
658 4878.818359375
659 4864.06103515625
660 4849.37158203125
661 4834.6083984375
662 4819.6943359375
663 4804.8662109375
664 4790.068359375
665 4775.44921875
666 4760.75048828125
667 4746.21484375
668 4731.6982421875
669 4717.3896484375
670 4702.91015625
671 4688.744140625
672 4674.44189453125
673 4660.4404296875
674 4646.1259765625
675 4632.23388671875
676 4618.216796875
677 4604.3212890625
678 4590.4482421875
679 4576.6484375
680 4562.91259765625
681 4549.1689453125
682 4535.6435546875
683 4522.01171875
684 4508.5234375
685 4495.02490234375
686 4481.54248046875
687 4468.25146484375
688 445

1061 1644.2021484375
1062 1640.3402099609375
1063 1636.4898681640625
1064 1632.63134765625
1065 1628.7388916015625
1066 1624.88427734375
1067 1621.1273193359375
1068 1617.2794189453125
1069 1613.4619140625
1070 1609.631103515625
1071 1605.93896484375
1072 1602.094482421875
1073 1598.3297119140625
1074 1594.603759765625
1075 1590.883544921875
1076 1587.1160888671875
1077 1583.3876953125
1078 1579.696044921875
1079 1576.0224609375
1080 1572.2933349609375
1081 1568.5989990234375
1082 1564.9766845703125
1083 1561.3201904296875
1084 1557.6383056640625
1085 1553.984375
1086 1550.45556640625
1087 1546.789794921875
1088 1543.1927490234375
1089 1539.5450439453125
1090 1536.0784912109375
1091 1532.421630859375
1092 1528.880859375
1093 1525.303955078125
1094 1521.8017578125
1095 1518.3021240234375
1096 1514.697509765625
1097 1511.24365234375
1098 1507.7840576171875
1099 1504.2601318359375
1100 1500.74853515625
1101 1497.319091796875
1102 1493.8533935546875
1103 1490.3697509765625
1104 1486.901977

1438 717.19287109375
1439 715.7457275390625
1440 714.2810668945312
1441 712.8095703125
1442 711.35986328125
1443 709.897216796875
1444 708.4526977539062
1445 707.0237426757812
1446 705.572509765625
1447 704.1363525390625
1448 702.6922607421875
1449 701.2637939453125
1450 699.8358764648438
1451 698.42431640625
1452 696.9984130859375
1453 695.5755615234375
1454 694.1616821289062
1455 692.751953125
1456 691.3446044921875
1457 689.9575805664062
1458 688.5438842773438
1459 687.15869140625
1460 685.7431640625
1461 684.3617553710938
1462 682.9879760742188
1463 681.6040649414062
1464 680.2140502929688
1465 678.8262329101562
1466 677.4669799804688
1467 676.0897216796875
1468 674.7440795898438
1469 673.3736572265625
1470 671.9944458007812
1471 670.64306640625
1472 669.2832641601562
1473 667.9420166015625
1474 666.5974731445312
1475 665.2467041015625
1476 663.8988647460938
1477 662.565185546875
1478 661.2214965820312
1479 659.9158935546875
1480 658.5682983398438
1481 657.23779296875
1482 655.9227

1916 288.25030517578125
1917 287.7393493652344
1918 287.22723388671875
1919 286.7073669433594
1920 286.210693359375
1921 285.68658447265625
1922 285.18316650390625
1923 284.67913818359375
1924 284.1690979003906
1925 283.665771484375
1926 283.1540832519531
1927 282.6585693359375
1928 282.158447265625
1929 281.64892578125
1930 281.14794921875
1931 280.6592712402344
1932 280.1517639160156
1933 279.6514587402344
1934 279.16473388671875
1935 278.6636962890625
1936 278.17041015625
1937 277.6804504394531
1938 277.18505859375
1939 276.6976013183594
1940 276.19647216796875
1941 275.71441650390625
1942 275.23101806640625
1943 274.73187255859375
1944 274.2555847167969
1945 273.7650146484375
1946 273.28082275390625
1947 272.79949951171875
1948 272.3193664550781
1949 271.8348083496094
1950 271.35455322265625
1951 270.8786315917969
1952 270.39898681640625
1953 269.9221496582031
1954 269.4428405761719
1955 268.976318359375
1956 268.493408203125
1957 268.021240234375
1958 267.555419921875
1959 267.077

2326 143.44313049316406
2327 143.20892333984375
2328 142.97630310058594
2329 142.74005126953125
2330 142.50965881347656
2331 142.27392578125
2332 142.04248046875
2333 141.81344604492188
2334 141.5755157470703
2335 141.35379028320312
2336 141.1143035888672
2337 140.8909912109375
2338 140.65579223632812
2339 140.42880249023438
2340 140.199462890625
2341 139.9697265625
2342 139.74282836914062
2343 139.51622009277344
2344 139.28585815429688
2345 139.0614776611328
2346 138.832275390625
2347 138.60968017578125
2348 138.3828125
2349 138.15414428710938
2350 137.93545532226562
2351 137.70492553710938
2352 137.48497009277344
2353 137.25692749023438
2354 137.03982543945312
2355 136.81515502929688
2356 136.58766174316406
2357 136.368408203125
2358 136.14837646484375
2359 135.9243927001953
2360 135.70541381835938
2361 135.47972106933594
2362 135.26693725585938
2363 135.04286193847656
2364 134.82427978515625
2365 134.60757446289062
2366 134.38641357421875
2367 134.1700439453125
2368 133.94921875
236

2729 75.57508850097656
2730 75.45953369140625
2731 75.3427505493164
2732 75.2261734008789
2733 75.10912322998047
2734 74.99413299560547
2735 74.87875366210938
2736 74.76376342773438
2737 74.64581298828125
2738 74.5320053100586
2739 74.4173355102539
2740 74.30361938476562
2741 74.18711853027344
2742 74.0731201171875
2743 73.95940399169922
2744 73.84378051757812
2745 73.73335266113281
2746 73.61614990234375
2747 73.50516510009766
2748 73.3913345336914
2749 73.27896881103516
2750 73.16398620605469
2751 73.05316162109375
2752 72.93989562988281
2753 72.8282699584961
2754 72.71566772460938
2755 72.60179138183594
2756 72.49424743652344
2757 72.37840270996094
2758 72.27014923095703
2759 72.1572265625
2760 72.04898834228516
2761 71.93617248535156
2762 71.82553100585938
2763 71.71574401855469
2764 71.60594177246094
2765 71.49545288085938
2766 71.38438415527344
2767 71.27715301513672
2768 71.16606140136719
2769 71.0573959350586
2770 70.9462890625
2771 70.83954620361328
2772 70.7301254272461
2773 

3128 41.405418395996094
3129 41.343994140625
3130 41.282806396484375
3131 41.22340393066406
3132 41.16127014160156
3133 41.101341247558594
3134 41.03947448730469
3135 40.98055648803711
3136 40.91972351074219
3137 40.85918426513672
3138 40.79924011230469
3139 40.73890686035156
3140 40.67969512939453
3141 40.61997985839844
3142 40.55875015258789
3143 40.49982833862305
3144 40.44051742553711
3145 40.38125228881836
3146 40.32084655761719
3147 40.262657165527344
3148 40.2032585144043
3149 40.143409729003906
3150 40.085227966308594
3151 40.02525329589844
3152 39.967647552490234
3153 39.9080696105957
3154 39.84937286376953
3155 39.791934967041016
3156 39.731937408447266
3157 39.67449188232422
3158 39.616180419921875
3159 39.55735397338867
3160 39.49919128417969
3161 39.441917419433594
3162 39.38493728637695
3163 39.32564926147461
3164 39.26792526245117
3165 39.211097717285156
3166 39.152103424072266
3167 39.09653854370117
3168 39.03782272338867
3169 38.980934143066406
3170 38.9244384765625
31

3572 21.79681396484375
3573 21.765432357788086
3574 21.73493766784668
3575 21.704652786254883
3576 21.67334747314453
3577 21.642799377441406
3578 21.611940383911133
3579 21.581504821777344
3580 21.55108070373535
3581 21.52042007446289
3582 21.489948272705078
3583 21.45965003967285
3584 21.429061889648438
3585 21.398897171020508
3586 21.368608474731445
3587 21.3387508392334
3588 21.307756423950195
3589 21.278850555419922
3590 21.247844696044922
3591 21.21796417236328
3592 21.18787956237793
3593 21.157808303833008
3594 21.128061294555664
3595 21.098901748657227
3596 21.067577362060547
3597 21.039440155029297
3598 21.008813858032227
3599 20.97907066345215
3600 20.949752807617188
3601 20.9201717376709
3602 20.890338897705078
3603 20.861495971679688
3604 20.83106231689453
3605 20.802398681640625
3606 20.7728214263916
3607 20.742748260498047
3608 20.71436882019043
3609 20.68478012084961
3610 20.655410766601562
3611 20.62652015686035
3612 20.597248077392578
3613 20.56798553466797
3614 20.5395

3957 12.729928016662598
3958 12.711904525756836
3959 12.694860458374023
3960 12.677449226379395
3961 12.65966796875
3962 12.642618179321289
3963 12.624759674072266
3964 12.607746124267578
3965 12.590561866760254
3966 12.572969436645508
3967 12.555421829223633
3968 12.538738250732422
3969 12.52071762084961
3970 12.504059791564941
3971 12.486881256103516
3972 12.469612121582031
3973 12.452396392822266
3974 12.435201644897461
3975 12.417974472045898
3976 12.401148796081543
3977 12.384202003479004
3978 12.366799354553223
3979 12.350083351135254
3980 12.33311939239502
3981 12.315793991088867
3982 12.2992582321167
3983 12.282194137573242
3984 12.265202522277832
3985 12.2486572265625
3986 12.231453895568848
3987 12.21475887298584
3988 12.198084831237793
3989 12.18112850189209
3990 12.16433334350586
3991 12.148067474365234
3992 12.131081581115723
3993 12.114625930786133
3994 12.097694396972656
3995 12.081144332885742
3996 12.064589500427246
3997 12.047819137573242
3998 12.031415939331055
3999 

4496 6.145500183105469
4497 6.1375837326049805
4498 6.129420757293701
4499 6.121297836303711
4500 6.113173961639404
4501 6.105083465576172
4502 6.09684419631958
4503 6.088793754577637
4504 6.080803871154785
4505 6.072614669799805
4506 6.0646281242370605
4507 6.056824684143066
4508 6.048651695251465
4509 6.0404438972473145
4510 6.032674789428711
4511 6.024615287780762
4512 6.016572952270508
4513 6.008611679077148
4514 6.000712871551514
4515 5.9928460121154785
4516 5.984717845916748
4517 5.976937294006348
4518 5.968903541564941
4519 5.961035251617432
4520 5.953197002410889
4521 5.945295333862305
4522 5.937272071838379
4523 5.929689884185791
4524 5.921740531921387
4525 5.91378116607666
4526 5.906009674072266
4527 5.898256301879883
4528 5.890305519104004
4529 5.882580757141113
4530 5.874953746795654
4531 5.867011547088623
4532 5.859182357788086
4533 5.851577281951904
4534 5.843729019165039
4535 5.835968017578125
4536 5.828461647033691
4537 5.820596694946289
4538 5.812764644622803
4539 5.80

4864 3.7916247844696045
4865 3.78666353225708
4866 3.7816505432128906
4867 3.776808261871338
4868 3.772003173828125
4869 3.76700758934021
4870 3.762057304382324
4871 3.757216453552246
4872 3.752397060394287
4873 3.747436046600342
4874 3.7426934242248535
4875 3.737757682800293
4876 3.7328743934631348
4877 3.728095054626465
4878 3.723280429840088
4879 3.718311309814453
4880 3.7135169506073
4881 3.708843946456909
4882 3.7040133476257324
4883 3.6991007328033447
4884 3.694312572479248
4885 3.6895911693573
4886 3.684722661972046
4887 3.6799535751342773
4888 3.675204277038574
4889 3.6705048084259033
4890 3.665647506713867
4891 3.660914897918701
4892 3.656203269958496
4893 3.6514182090759277
4894 3.646657705307007
4895 3.6420130729675293
4896 3.637253761291504
4897 3.6325111389160156
4898 3.627807378768921
4899 3.6231465339660645
4900 3.618408203125
4901 3.6136765480041504
4902 3.609133720397949
4903 3.604339122772217
4904 3.5996499061584473
4905 3.594992160797119
4906 3.5903518199920654
4907 

5275 2.234818458557129
5276 2.231950521469116
5277 2.2291646003723145
5278 2.226283073425293
5279 2.2234480381011963
5280 2.2206077575683594
5281 2.217827320098877
5282 2.214927911758423
5283 2.212167501449585
5284 2.209397315979004
5285 2.2065491676330566
5286 2.2037274837493896
5287 2.2009334564208984
5288 2.198155164718628
5289 2.195314884185791
5290 2.1925158500671387
5291 2.18978214263916
5292 2.1870574951171875
5293 2.184220552444458
5294 2.1813836097717285
5295 2.1786513328552246
5296 2.1759109497070312
5297 2.173114776611328
5298 2.170372486114502
5299 2.1675801277160645
5300 2.1648757457733154
5301 2.162111759185791
5302 2.159346103668213
5303 2.156642436981201
5304 2.153904676437378
5305 2.15114688873291
5306 2.1484413146972656
5307 2.1457033157348633
5308 2.142984628677368
5309 2.140221118927002
5310 2.1375155448913574
5311 2.134805679321289
5312 2.1320760250091553
5313 2.1293838024139404
5314 2.1267318725585938
5315 2.1240477561950684
5316 2.1213133335113525
5317 2.11860370

5688 1.3279895782470703
5689 1.3263520002365112
5690 1.3247294425964355
5691 1.3230445384979248
5692 1.3213675022125244
5693 1.3197320699691772
5694 1.3181105852127075
5695 1.3164761066436768
5696 1.3147896528244019
5697 1.3131495714187622
5698 1.3115342855453491
5699 1.309905767440796
5700 1.3082962036132812
5701 1.3066047430038452
5702 1.3049930334091187
5703 1.3033943176269531
5704 1.3017663955688477
5705 1.3001033067703247
5706 1.2984833717346191
5707 1.2968727350234985
5708 1.295287013053894
5709 1.2936533689498901
5710 1.2920033931732178
5711 1.2904384136199951
5712 1.2888363599777222
5713 1.2872086763381958
5714 1.2855756282806396
5715 1.2839864492416382
5716 1.2824149131774902
5717 1.280813217163086
5718 1.2792022228240967
5719 1.27759850025177
5720 1.2760318517684937
5721 1.2744388580322266
5722 1.272831678390503
5723 1.271242618560791
5724 1.269655466079712
5725 1.2681071758270264
5726 1.2665154933929443
5727 1.2649022340774536
5728 1.263349175453186
5729 1.2617923021316528
5

6072 0.8257169127464294
6073 0.8247087001800537
6074 0.8236894011497498
6075 0.8226839303970337
6076 0.8216685056686401
6077 0.8206642866134644
6078 0.8196637630462646
6079 0.8186867237091064
6080 0.8176489472389221
6081 0.8166567087173462
6082 0.8156505227088928
6083 0.8146660327911377
6084 0.8136616945266724
6085 0.8126599192619324
6086 0.8116381764411926
6087 0.8106629252433777
6088 0.8096761107444763
6089 0.8086841106414795
6090 0.8076817989349365
6091 0.806693434715271
6092 0.8057066798210144
6093 0.8047240376472473
6094 0.8037388324737549
6095 0.80274897813797
6096 0.801774799823761
6097 0.8008057475090027
6098 0.7998018264770508
6099 0.7988436222076416
6100 0.797846794128418
6101 0.7968725562095642
6102 0.7958860397338867
6103 0.7949296236038208
6104 0.7939428091049194
6105 0.7929792404174805
6106 0.7919925451278687
6107 0.7910454869270325
6108 0.790067732334137
6109 0.7891094088554382
6110 0.7881150245666504
6111 0.7871674299240112
6112 0.7861929535865784
6113 0.785252213478088

6481 0.5023240447044373
6482 0.5017244815826416
6483 0.5011255145072937
6484 0.500527024269104
6485 0.49992138147354126
6486 0.49932342767715454
6487 0.4987107217311859
6488 0.49811309576034546
6489 0.49752476811408997
6490 0.4969155490398407
6491 0.4963192641735077
6492 0.4957219660282135
6493 0.4951355457305908
6494 0.4945336878299713
6495 0.4939326047897339
6496 0.49333590269088745
6497 0.49274370074272156
6498 0.4921645224094391
6499 0.49156516790390015
6500 0.49097388982772827
6501 0.49037933349609375
6502 0.4897904396057129
6503 0.4891994893550873
6504 0.4886245131492615
6505 0.48802900314331055
6506 0.4874458312988281
6507 0.4868570566177368
6508 0.48627933859825134
6509 0.4856836795806885
6510 0.4850969910621643
6511 0.48452720046043396
6512 0.48394617438316345
6513 0.483361154794693
6514 0.4827946424484253
6515 0.4821970462799072
6516 0.48163220286369324
6517 0.4810433089733124
6518 0.48048585653305054
6519 0.47988367080688477
6520 0.4793044626712799
6521 0.47873455286026
6522

6907 0.3025650978088379
6908 0.30221444368362427
6909 0.3018532395362854
6910 0.30149519443511963
6911 0.30114293098449707
6912 0.30078455805778503
6913 0.3004324436187744
6914 0.30008405447006226
6915 0.29972973465919495
6916 0.2993764579296112
6917 0.29902446269989014
6918 0.29867491126060486
6919 0.2983309030532837
6920 0.2979767322540283
6921 0.2976232171058655
6922 0.29727548360824585
6923 0.2969249188899994
6924 0.29658451676368713
6925 0.2962217628955841
6926 0.2958749234676361
6927 0.29553478956222534
6928 0.2951798439025879
6929 0.2948381304740906
6930 0.29449930787086487
6931 0.29414477944374084
6932 0.2937994599342346
6933 0.293459415435791
6934 0.2931102216243744
6935 0.2927626669406891
6936 0.29242607951164246
6937 0.2920758128166199
6938 0.29173386096954346
6939 0.2913931906223297
6940 0.29105401039123535
6941 0.2907048165798187
6942 0.2903708517551422
6943 0.2900279462337494
6944 0.28968632221221924
6945 0.28934746980667114
6946 0.28899624943733215
6947 0.288660973310470

7344 0.18201449513435364
7345 0.18180786073207855
7346 0.18159839510917664
7347 0.18138860166072845
7348 0.1811792105436325
7349 0.1809716671705246
7350 0.18076764047145844
7351 0.18055787682533264
7352 0.18035492300987244
7353 0.1801430881023407
7354 0.179933100938797
7355 0.1797291338443756
7356 0.17953184247016907
7357 0.1793205589056015
7358 0.1791173368692398
7359 0.17891359329223633
7360 0.17870593070983887
7361 0.17850472033023834
7362 0.17829516530036926
7363 0.1780855357646942
7364 0.17788547277450562
7365 0.17767882347106934
7366 0.1774851381778717
7367 0.1772765815258026
7368 0.17707540094852448
7369 0.17686979472637177
7370 0.17666417360305786
7371 0.17645788192749023
7372 0.1762571930885315
7373 0.17605945467948914
7374 0.17586365342140198
7375 0.17565421760082245
7376 0.1754555106163025
7377 0.17525742948055267
7378 0.1750578135251999
7379 0.17485231161117554
7380 0.17465248703956604
7381 0.1744554340839386
7382 0.1742582619190216
7383 0.17406103014945984
7384 0.173855125

7769 0.11243221908807755
7770 0.1123066321015358
7771 0.11217747628688812
7772 0.11205433309078217
7773 0.11193042248487473
7774 0.11180488765239716
7775 0.11167740821838379
7776 0.11155181378126144
7777 0.11142703145742416
7778 0.11130102723836899
7779 0.11117366701364517
7780 0.11105044186115265
7781 0.11092761158943176
7782 0.1108008325099945
7783 0.1106780394911766
7784 0.11054995656013489
7785 0.1104281023144722
7786 0.11030785739421844
7787 0.11018207669258118
7788 0.11006054282188416
7789 0.10993541777133942
7790 0.10981105268001556
7791 0.10968843102455139
7792 0.10956374555826187
7793 0.10944119840860367
7794 0.10932058840990067
7795 0.1091933622956276
7796 0.10907267034053802
7797 0.10895019769668579
7798 0.10882822424173355
7799 0.10870877653360367
7800 0.10858546942472458
7801 0.1084664836525917
7802 0.10834792256355286
7803 0.108223095536232
7804 0.10809824615716934
7805 0.10797843337059021
7806 0.10785980522632599
7807 0.1077391505241394
7808 0.10761740058660507
7809 0.10

8182 0.07121844589710236
8183 0.07114005088806152
8184 0.07106531411409378
8185 0.07098536193370819
8186 0.0709107369184494
8187 0.07083368301391602
8188 0.0707566887140274
8189 0.07067746669054031
8190 0.0706048235297203
8191 0.07052437961101532
8192 0.07044880092144012
8193 0.07037371397018433
8194 0.07029485702514648
8195 0.07022039592266083
8196 0.07014574855566025
8197 0.0700707659125328
8198 0.06999540328979492
8199 0.0699169784784317
8200 0.0698390007019043
8201 0.06976521760225296
8202 0.06969375163316727
8203 0.06961347907781601
8204 0.06953755766153336
8205 0.06946417689323425
8206 0.06938939541578293
8207 0.069313183426857
8208 0.06923729926347733
8209 0.06916363537311554
8210 0.06908781826496124
8211 0.06901498883962631
8212 0.06893948465585709
8213 0.06886560469865799
8214 0.06879132241010666
8215 0.06871622800827026
8216 0.06863968074321747
8217 0.068568155169487
8218 0.06849092245101929
8219 0.06841843575239182
8220 0.06834612786769867
8221 0.06827052682638168
8222 0.068

8589 0.04614526778459549
8590 0.04609934240579605
8591 0.04605397209525108
8592 0.046004459261894226
8593 0.045952849090099335
8594 0.04590659588575363
8595 0.04585668072104454
8596 0.04580863565206528
8597 0.04576212540268898
8598 0.04571431875228882
8599 0.045667968690395355
8600 0.045619428157806396
8601 0.045570239424705505
8602 0.0455215722322464
8603 0.04547501727938652
8604 0.04542740434408188
8605 0.04537878930568695
8606 0.04533389210700989
8607 0.045286186039447784
8608 0.04523993656039238
8609 0.04519122838973999
8610 0.045145124197006226
8611 0.045096490532159805
8612 0.04504779726266861
8613 0.04500235617160797
8614 0.044955380260944366
8615 0.04490980505943298
8616 0.04486345872282982
8617 0.044814545661211014
8618 0.04476802796125412
8619 0.04472152143716812
8620 0.04467425495386124
8621 0.04462742805480957
8622 0.04458393156528473
8623 0.04453752189874649
8624 0.04448919743299484
8625 0.044444262981414795
8626 0.044396284967660904
8627 0.04435001313686371
8628 0.0443045

9012 0.029927702620625496
9013 0.029899626970291138
9014 0.02986992709338665
9015 0.02983923628926277
9016 0.029810706153512
9017 0.029779158532619476
9018 0.02975134551525116
9019 0.029720213264226913
9020 0.029690828174352646
9021 0.029661383479833603
9022 0.02963005006313324
9023 0.029600638896226883
9024 0.029570484533905983
9025 0.029542867094278336
9026 0.02951326034963131
9027 0.029482798650860786
9028 0.029455173760652542
9029 0.029426272958517075
9030 0.02939615398645401
9031 0.029367784038186073
9032 0.02933827042579651
9033 0.0293082557618618
9034 0.029277440160512924
9035 0.029248394072055817
9036 0.02921704575419426
9037 0.02918810397386551
9038 0.029161209240555763
9039 0.0291342344135046
9040 0.029103804379701614
9041 0.02907562255859375
9042 0.029046304523944855
9043 0.029016930609941483
9044 0.02898760512471199
9045 0.028958970680832863
9046 0.02892884984612465
9047 0.028902152553200722
9048 0.02887408435344696
9049 0.028846271336078644
9050 0.02881479822099209
9051 0.

9411 0.020251937210559845
9412 0.020231662318110466
9413 0.020212562754750252
9414 0.020193880423903465
9415 0.02017504721879959
9416 0.02015496790409088
9417 0.020135633647441864
9418 0.020116275176405907
9419 0.02009761519730091
9420 0.020076824352145195
9421 0.020059291273355484
9422 0.020038608461618423
9423 0.0200202539563179
9424 0.020000871270895004
9425 0.01998116634786129
9426 0.019962221384048462
9427 0.01994330808520317
9428 0.019923396408557892
9429 0.0199048463255167
9430 0.019886408001184464
9431 0.019868381321430206
9432 0.01984862983226776
9433 0.01983070932328701
9434 0.01981043815612793
9435 0.0197922233492136
9436 0.019772225990891457
9437 0.019754886627197266
9438 0.019735615700483322
9439 0.01971639320254326
9440 0.019696518778800964
9441 0.01967882551252842
9442 0.019660338759422302
9443 0.01963954046368599
9444 0.01962154358625412
9445 0.01960442215204239
9446 0.019586432725191116
9447 0.01956719160079956
9448 0.019547978416085243
9449 0.01953059993684292
9450 0.

9764 0.01455521397292614
9765 0.01454242505133152
9766 0.014527970924973488
9767 0.014515680260956287
9768 0.014503373764455318
9769 0.014489672146737576
9770 0.014476094394922256
9771 0.014462975785136223
9772 0.0144497100263834
9773 0.014436028897762299
9774 0.01442328467965126
9775 0.01440993882715702
9776 0.014396872371435165
9777 0.014383463189005852
9778 0.0143702682107687
9779 0.014357062987983227
9780 0.01434399839490652
9781 0.014331532642245293
9782 0.01431841216981411
9783 0.014306195080280304
9784 0.01429351232945919
9785 0.014280333183705807
9786 0.014266042038798332
9787 0.014253772795200348
9788 0.014239704236388206
9789 0.01422862894833088
9790 0.014214740134775639
9791 0.014201907441020012
9792 0.014188881032168865
9793 0.01417590957134962
9794 0.014162993989884853
9795 0.01415092870593071
9796 0.014137570746243
9797 0.014124948531389236
9798 0.01411128044128418
9799 0.014098618179559708
9800 0.014086735434830189
9801 0.014072826132178307
9802 0.014060791581869125
9803